spring:
  datasource:
    url: jdbc:mysql://47.92.224.70:15306/moon?useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=falsie&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=CONVERT_TO_NULL&allowPublicKeyRetrieval=true&pinGlobalTxToPhysicalConnection=true&useSSL=false
    username: kunpeng
    password: Zh5715615~

web3:
  account:
    encrypt-password: "lcHVSyAG4VHhALrcTiE10Q=="
    address: "0xa24bDb249e80574A96D8B02b148E81B9be684675"
  url: "https://go.getblock.io/aaefaf5b1ccb4b64901988b3899efff9"
  chain-id: 97
  gas-fee:
    price: "100000000000"
    limit: "3000000"
  contract:
    usdt:
      address: "0x5B32Cc7d18643073BDB15dAfafC5C35E736c91a5"
    space-jedi:
      address: "0x7ef3D2a397cd368A33d35c52Db42013f691aa7C7"
    card-nft:
      address: "0x43B2955aF88BCb97a60E749ac1A24377780674E0"
    dapp-pool:
      address: "0xF70838d2e1345b905369608cB6cdD1fB22fe2298"

star-wars:
  login:
    timestamp-check: false
  promote-reward-percentage: 0.1
  jwt:
    expired: 300 # 5分钟
  auth:
    enable: false
  oss:
    access-key: t8lJh36BE4eJIaUZJYpc
    secret-key: vy5tuYaDMTAdFmkAfkNs03WbPywK2jxXgdBE4NHP
    domain: 43.155.129.126:9000
    endpoint: http://43.155.129.126:9000
    region: us-east-1
    is-https: N
    access-policy: 0
  secret:
    aes-key: abcd9876ABWE!@#$

logging:
  level:
    tcbv.zhaohui.moon. dao: debug